### ISSUE TITLE
/c_programs/matrixmath.c has issue with scanf

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/random_c_cpp_programs#19]
I am getting an issue with matrixmath.c and the use of scanf..

IntelliSense says:

Call to function 'scanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'scanf_s' in case of C11C/C++[clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling](https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/clang-analyzer/security.insecureAPI.DeprecatedOrUnsafeBufferHandling.html)
matrixmath.c(15, 13): Call to function 'scanf' is insecure as it does not provide security checks introduced in the C11 standard. Replace with analogous functions that support length arguments or provides boundary checks such as 'scanf_s' in case of C11
int scanf(const char *__restrict__ __format, ...)
Read formatted input from stdin.

This function is a possible cancellation point and therefore not
marked with __THROW.

**Comment by andrewlod** [comment]
Unfortunately `scanf_s` is only available to Microsoft compilers. However, as the default C version is already C11 according to the project settings, these security checks will be included when you compile the code and no warnings will appear. If you use VSCode, you can dismiss the warning by hovering your mouse over the function > `Quick fix` > `Disable all clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling problems`.

**Comment by gbowne1** [comment]
@andrewlod 

My current development machine is a Linux PC with Debian x86_64.  

Is there an easier way to fix this?  At the time I wrote this, scanf/scanf_s is the only thing I could think of that might work.

I have GNU 8.3.0 installed with libc11, gcc, g++, clang, clang-tidy, clang-format, etc. etc.  If this a compiler type issue, then maybe we write a version for Windows and a version for POSIX/Linux/Unix.

**Comment by andrewlod** [comment]
I have done some research and found the following options:
1)  Use `#define _CRT_SECURE_NO_WARNINGS` in the beginning of the code. It will not affect IntelliSense, but if the problem is related to the compiler complaining about the issue, it solves the problem.
2) Create your own implementation of scanf, maybe with `gets()` or `getchar()`. Note: `gets()` has the same buffer overflow problem as `scanf()`, so probably not very useful.
3) Validate input after `scanf()`: `if (input == EOF) //throw some error`

I have GCC 11 and compiled the code with `gcc matrixmath.c --std=c11 -o matrixmath`

**Comment by gbowne1** [comment]
I would be inclined to do #1.  I didn't do any tests on this to see if this particular program had any other issues.
